### ISSUE TITLE
TSD is deprecated, update to typings instead

### ISSUE THREAD

**Issue by ayxos** [toddlucas/react-tsx-starter#2]
https://github.com/typings/typings

Great job!

**Comment by toddlucas** [comment]
Thanks for the note. This is something that is on my list of things to do. I plan on switching very soon. Cheers!

**Comment by toddlucas** [comment]
You may have seen this post from earlier today: [The Future of Declaration Files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).

Given that npm will be the standard way of managing types in the near future, I may wait rather than move to typings, only to move npm shortly thereafter.
