### ISSUE TITLE
Tsx files?

### ISSUE THREAD

**Issue by omidahourai** [toddlucas/react-tsx-starter#3]
Hi @toddlucas - I'm new to Typescript (and vscode too). Taking a look at your project, I'm not sure why vscode isn't playing nicely with the tsx files, any ideas? See screenshot below, appreciate your help!

![image](https://cloud.githubusercontent.com/assets/705001/20651663/2455592e-b49e-11e6-9522-5f41be368c57.png)

**Comment by toddlucas** [comment]
Hi @ArdentKid, Thanks for trying the starter! First, I wanted to double check that you have run `npm install` and `typings install` as outlined in the README.

There are two problems that you're seeing here, and I've tried different solutions to them. Unfortunately, I don't have a good general purpose answer, yet. The two problems are:

1. The TypeScript compiler is having trouble locating the typings files
2. The compiler is not getting the `--jsx` flag when building IntelliSense

Initially, it looked like tsconfig.json might be the answer. You can see that there are two entries in the file that attempt to feed the compiler some parameters. It appears to be working for builds, but I'm not sure the IntelliSense protocol is using it (VS Code spins up a background TypeScript process to supply IntelliSense using an open protocol that MS has developed).

It is possible to work around the import warning by adding a reference comment to the top of each file, as you can see in `server.tsx`. It looks like this:

```
/// <reference path="../typings/index.d.ts"/>
```

Although this is a pain, it should only require one line, since the `typings` utility combines references for you in `index.d.ts`. You'll need to fix up the relative path, of course, depending on the depth of the `.tsx` file.

As for the `--jsx` issue, I don't have a solution, yet. There are others who have filed issues, so maybe we'll get some resolution at some point (hopefully soon).

**Comment by ehartford** [comment]
I learned, for all the react types, don't install "npm install --save-dev @types/react-*"
instead, use "typings install react-* -save"
